spring.application.name=ems-backend

# configure ( tell spring-boot about database )
#which database to connect with :
spring.datasource.url=jdbc:mysql://localhost:3306/ems
spring.datasource.username=root
spring.datasource.password=Abhi123

#but what database language will be use to create sql statements ?
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# If Any changes in Entity Do you want to reflect that into DB ?
spring.jpa.hibernate.ddl-auto=update
